---
# tasks file for awscli

- name: Install pip awscli package
  pip:
    name: 'awscli'
    state: 'latest'
  when: awscli_version == 'latest'
  tags:
    - awscli

- name: Install pip awscli package
  pip:
    name: 'awscli'
    state: 'present'
    version: '{{ awscli_version }}'
  when: awscli_version != 'latest'
  tags:
    - awscli

- name: Enable tab completion for awscli
  copy:
    src: 'aws-cli.sh'
    dest: '/etc/profile.d/aws-cli.sh'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: awscli_enable_tab_completion
  tags:
    - awscli

- block:
    - name: Ensure .aws dir exists and belongs to {{ awscli_user }}
      file:
        path: '~{{ awscli_user }}/.aws'
        state: 'directory'
        owner: '{{ awscli_user }}'
        group: '{{ awscli_group|default(awscli_user) }}'
        mode: '0755'

    - name: Create awscli config file
      template:
        src: 'config.j2'
        dest: '~{{ awscli_user }}/.aws/config'
        owner: '{{ awscli_user }}'
        group: '{{ awscli_group|default(awscli_user) }}'
        mode: '0644'
  when: awscli_user is defined
  tags:
    - awscli

- name: Check if Session Manager Plugin package is installed
  shell: >
    dpkg-query -W session-manager-plugin
  register: awscli_sessionmanagerplugin_check_deb
  failed_when: awscli_sessionmanagerplugin_check_deb.rc > 1
  changed_when: awscli_sessionmanagerplugin_check_deb.rc == 1

- name: Install Session Manager Plugin package
  apt:
    deb: 'https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb'
  when: awscli_sessionmanagerplugin_check_deb.rc == 1
